#!/usr/bin/env python3
"""
build_executed_route_viz.py — Interactive visualization of actual executed vehicle routes
==========================================================================================
Reads executed_routes.json (generated by ExecutedRouteRecorder) and produces a
self-contained HTML page with:
  - Vehicle selector with route statistics
  - Timeline view with detailed node cards (arrive/leave, deliveries, pickups, carrying)
  - Route summary and statistics

Usage:
    python build_executed_route_viz.py <executed_routes.json> [output.html]
    
    python build_executed_route_viz.py visualization_output/instance_1/executed_routes.json
    python build_executed_route_viz.py visualization_output/instance_1/executed_routes.json my_viz.html
"""

import datetime
import json
import os
import sys
import html as html_mod


# ── Color palette for vehicles ──
VEHICLE_COLORS = [
    '#e6194b', '#3cb44b', '#4363d8', '#f58231', '#911eb4',
    '#42d4f4', '#f032e6', '#bfef45', '#fabebe', '#469990',
    '#e6beff', '#9a6324', '#800000', '#aaffc3', '#808000',
    '#ffd8b1', '#000075', '#a9a9a9', '#ffd700', '#00ffff',
]


def fmt_ts(ts: int) -> str:
    """Format unix timestamp as HH:MM."""
    if ts <= 0:
        return '--:--'
    return datetime.datetime.fromtimestamp(ts).strftime('%H:%M')


def fmt_datetime(ts: int) -> str:
    """Format unix timestamp as full datetime."""
    if ts <= 0:
        return 'N/A'
    return datetime.datetime.fromtimestamp(ts).strftime('%Y-%m-%d %H:%M:%S')


def fmt_duration(seconds: int) -> str:
    """Format duration in human-readable form."""
    if seconds < 60:
        return f"{seconds}s"
    elif seconds < 3600:
        return f"{seconds // 60}m {seconds % 60}s"
    else:
        h = seconds // 3600
        m = (seconds % 3600) // 60
        return f"{h}h {m}m"


def render_node_card(node: dict, node_index: int, vehicle_color: str, factory_data: dict) -> str:
    """Render a single executed node as an HTML card."""
    fid = node['factory_id']
    arrive = node['arrive_time']
    leave = node['leave_time']
    service = node.get('service_time', 0)
    deliveries = node.get('delivery_items', [])
    pickups = node.get('pickup_items', [])
    carrying = node.get('carrying_after', [])

    # Factory info
    factory = factory_data.get(fid, {})
    dock = factory.get('dock_num', '?')

    # Duration
    duration = leave - arrive if arrive > 0 and leave > 0 else 0

    # Build card HTML
    parts = []
    parts.append(f'<div class="node-card" style="border-left: 4px solid {vehicle_color};">')

    # Header
    parts.append(f'<div class="node-header">')
    parts.append(f'<span class="node-index">#{node_index + 1}</span>')
    parts.append(f'<span class="node-factory">{html_mod.escape(fid)}</span>')
    parts.append(f'<span class="node-dock">🅿️ {dock} docks</span>')
    parts.append(f'</div>')

    # Time row
    parts.append(f'<div class="node-time">')
    parts.append(f'<span class="time-label">🕐</span>')
    parts.append(f'<span class="time-value">{fmt_ts(arrive)} → {fmt_ts(leave)}</span>')
    parts.append(f'<span class="time-duration">({fmt_duration(duration)})</span>')
    if service > 0:
        parts.append(f'<span class="time-service">⚙️ Service: {fmt_duration(service)}</span>')
    parts.append(f'</div>')

    # Delivery items
    if deliveries:
        parts.append(f'<div class="node-items node-deliveries">')
        parts.append(f'<span class="item-icon">📥</span>')
        parts.append(f'<span class="item-label">Deliver ({len(deliveries)}):</span>')
        item_tags = []
        for item in deliveries:
            oid = item.get('order_id', '?')
            iid = item.get('item_id', '?')
            itype = item.get('type', '?')
            item_tags.append(
                f'<span class="item-tag delivery-tag" title="Order: {oid}">'
                f'{html_mod.escape(str(iid))} <small>({html_mod.escape(str(itype))})</small>'
                f'</span>'
            )
        parts.append(f'<div class="item-tags">{" ".join(item_tags)}</div>')
        parts.append(f'</div>')

    # Pickup items
    if pickups:
        parts.append(f'<div class="node-items node-pickups">')
        parts.append(f'<span class="item-icon">📤</span>')
        parts.append(f'<span class="item-label">Pickup ({len(pickups)}):</span>')
        item_tags = []
        for item in pickups:
            oid = item.get('order_id', '?')
            iid = item.get('item_id', '?')
            itype = item.get('type', '?')
            item_tags.append(
                f'<span class="item-tag pickup-tag" title="Order: {oid}">'
                f'{html_mod.escape(str(iid))} <small>({html_mod.escape(str(itype))})</small>'
                f'</span>'
            )
        parts.append(f'<div class="item-tags">{" ".join(item_tags)}</div>')
        parts.append(f'</div>')

    # Carrying after
    if carrying:
        count = len(carrying)
        preview = carrying[:5]
        more = f' +{len(carrying) - 5}' if len(carrying) > 5 else ''
        parts.append(f'<div class="node-carrying">')
        parts.append(f'<span class="carrying-icon">🚛</span>')
        parts.append(f'<span class="carrying-label">Carrying ({count}):</span>')
        parts.append(
            f'<span class="carrying-items">'
            f'{", ".join(html_mod.escape(str(x)) for x in preview)}{more}'
            f'</span>'
        )
        parts.append(f'</div>')

    parts.append(f'</div>')  # close node-card
    return '\n'.join(parts)


def render_vehicle_summary(vehicle_id: str, nodes: list, color: str) -> str:
    """Render the summary stats for a vehicle."""
    total = len(nodes)
    if total == 0:
        return f'<div class="vehicle-summary-card" style="border-color:{color}">' \
               f'<strong>{html_mod.escape(vehicle_id)}</strong><br>0 nodes</div>'

    # Time span
    first_arrive = nodes[0]['arrive_time']
    last_leave = nodes[-1]['leave_time']
    time_span = last_leave - first_arrive if first_arrive > 0 and last_leave > 0 else 0

    # Total deliveries and pickups
    total_del = sum(len(n.get('delivery_items', [])) for n in nodes)
    total_pup = sum(len(n.get('pickup_items', [])) for n in nodes)

    # Unique factories visited
    factories = set(n['factory_id'] for n in nodes)

    return f'''
    <div class="vehicle-summary-card" style="border-left: 5px solid {color};" 
         onclick="selectVehicle('{vehicle_id}')" id="card-{vehicle_id}">
        <div class="vsc-header">
            <span class="vsc-dot" style="background:{color}"></span>
            <span class="vsc-name">{html_mod.escape(vehicle_id)}</span>
            <span class="vsc-nodes">{total} nodes</span>
        </div>
        <div class="vsc-body">
            <div class="vsc-stat">🏭 {len(factories)} factories</div>
            <div class="vsc-stat">📥 {total_del} del | 📤 {total_pup} pup</div>
            <div class="vsc-stat">⏱️ {fmt_duration(time_span)}</div>
        </div>
    </div>
    '''


def generate_html(data: dict) -> str:
    """Generate the complete HTML page."""
    instance = data.get('instance', 'Unknown')
    vehicles = data.get('vehicles', {})
    factory_list = data.get('factory_data', [])
    generated_at = data.get('generated_at', 'N/A')

    # Build factory lookup
    factory_data = {f['id']: f for f in factory_list}

    # Assign colors to vehicles
    vehicle_colors = {}
    for i, vid in enumerate(sorted(vehicles.keys())):
        vehicle_colors[vid] = VEHICLE_COLORS[i % len(VEHICLE_COLORS)]

    # Count total nodes
    total_nodes = sum(v['total_nodes'] for v in vehicles.values())

    # ── Build vehicle sidebar ──
    sidebar_cards = []
    for vid in sorted(vehicles.keys()):
        vdata = vehicles[vid]
        nodes = vdata.get('executed_nodes', [])
        color = vehicle_colors.get(vid, '#999')
        sidebar_cards.append(render_vehicle_summary(vid, nodes, color))
    sidebar_html = '\n'.join(sidebar_cards)

    # ── Build route details (one per vehicle, hidden by default) ──
    route_sections = []
    for vid in sorted(vehicles.keys()):
        vdata = vehicles[vid]
        nodes = vdata.get('executed_nodes', [])
        color = vehicle_colors.get(vid, '#999')

        node_cards = []
        for i, node in enumerate(nodes):
            node_cards.append(render_node_card(node, i, color, factory_data))

        # Stats
        total_del = sum(len(n.get('delivery_items', [])) for n in nodes)
        total_pup = sum(len(n.get('pickup_items', [])) for n in nodes)
        factories_set = set(n['factory_id'] for n in nodes)

        section_html = f'''
        <div class="route-section" id="route-{vid}" style="display:none;">
            <div class="route-header" style="background: {color}20; border-bottom: 3px solid {color};">
                <h2>🚛 {html_mod.escape(vid)} — Executed Route</h2>
                <div class="route-stats">
                    <span>🏭 {len(factories_set)} factories</span>
                    <span>📦 {total_del + total_pup} operations</span>
                    <span>📥 {total_del} deliveries</span>
                    <span>📤 {total_pup} pickups</span>
                    <span>🔢 {len(nodes)} nodes</span>
                </div>
            </div>
            <div class="node-list">
                {"".join(node_cards) if node_cards else '<p class="empty-msg">No executed nodes recorded for this vehicle.</p>'}
            </div>
        </div>
        '''
        route_sections.append(section_html)
    routes_html = '\n'.join(route_sections)

    # ── Full HTML ──
    return f'''<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>DPDP Executed Routes — {html_mod.escape(instance)}</title>
<style>
    * {{ margin: 0; padding: 0; box-sizing: border-box; }}
    body {{
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
        background: #f0f2f5;
        color: #333;
        display: flex;
        flex-direction: column;
        height: 100vh;
    }}

    /* ── Top bar ── */
    .top-bar {{
        background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
        color: #fff;
        padding: 12px 24px;
        display: flex;
        align-items: center;
        justify-content: space-between;
        flex-shrink: 0;
    }}
    .top-bar h1 {{ font-size: 20px; font-weight: 600; }}
    .top-bar .meta {{ font-size: 12px; opacity: 0.7; }}

    /* ── Main layout ── */
    .main-container {{
        display: flex;
        flex: 1;
        overflow: hidden;
    }}

    /* ── Sidebar ── */
    .sidebar {{
        width: 320px;
        min-width: 320px;
        background: #fff;
        border-right: 1px solid #e0e0e0;
        overflow-y: auto;
        padding: 12px;
    }}
    .sidebar h3 {{
        font-size: 14px;
        text-transform: uppercase;
        letter-spacing: 1px;
        color: #888;
        padding: 8px 4px;
        margin-bottom: 8px;
    }}

    /* ── Vehicle summary card ── */
    .vehicle-summary-card {{
        background: #fafafa;
        border-radius: 8px;
        padding: 12px;
        margin-bottom: 8px;
        cursor: pointer;
        transition: all 0.2s;
        border: 1px solid #e8e8e8;
    }}
    .vehicle-summary-card:hover {{
        background: #f0f4ff;
        transform: translateX(2px);
        box-shadow: 0 2px 8px rgba(0,0,0,0.1);
    }}
    .vehicle-summary-card.active {{
        background: #e8f0fe;
        border-color: #4363d8;
        box-shadow: 0 2px 12px rgba(67,99,216,0.2);
    }}
    .vsc-header {{
        display: flex;
        align-items: center;
        gap: 8px;
        margin-bottom: 6px;
    }}
    .vsc-dot {{
        width: 10px; height: 10px;
        border-radius: 50%;
        flex-shrink: 0;
    }}
    .vsc-name {{ font-weight: 600; font-size: 14px; }}
    .vsc-nodes {{
        margin-left: auto;
        font-size: 12px;
        background: #e0e0e0;
        padding: 2px 8px;
        border-radius: 10px;
    }}
    .vsc-body {{ font-size: 12px; color: #666; }}
    .vsc-stat {{ display: inline-block; margin-right: 10px; }}

    /* ── Content area ── */
    .content {{
        flex: 1;
        overflow-y: auto;
        padding: 20px 24px;
    }}

    /* ── Route section ── */
    .route-header {{
        padding: 16px 20px;
        border-radius: 10px 10px 0 0;
        margin-bottom: 0;
    }}
    .route-header h2 {{
        font-size: 18px;
        margin-bottom: 8px;
    }}
    .route-stats {{
        display: flex;
        gap: 16px;
        font-size: 13px;
        color: #555;
    }}
    .route-stats span {{
        background: #fff;
        padding: 3px 10px;
        border-radius: 12px;
        border: 1px solid #ddd;
    }}

    /* ── Node card ── */
    .node-list {{
        display: flex;
        flex-direction: column;
        gap: 8px;
        padding: 12px 0;
    }}
    .node-card {{
        background: #fff;
        border-radius: 8px;
        padding: 14px 16px;
        box-shadow: 0 1px 4px rgba(0,0,0,0.06);
        transition: box-shadow 0.2s;
    }}
    .node-card:hover {{
        box-shadow: 0 3px 12px rgba(0,0,0,0.12);
    }}
    .node-header {{
        display: flex;
        align-items: center;
        gap: 10px;
        margin-bottom: 8px;
    }}
    .node-index {{
        background: #4363d8;
        color: #fff;
        font-size: 11px;
        font-weight: 700;
        padding: 2px 8px;
        border-radius: 10px;
    }}
    .node-factory {{
        font-weight: 600;
        font-size: 15px;
        font-family: 'SF Mono', 'Consolas', monospace;
    }}
    .node-dock {{
        margin-left: auto;
        font-size: 12px;
        color: #888;
    }}
    .node-time {{
        display: flex;
        align-items: center;
        gap: 8px;
        font-size: 13px;
        color: #555;
        margin-bottom: 6px;
    }}
    .time-duration {{
        color: #888;
        font-size: 12px;
    }}
    .time-service {{
        margin-left: auto;
        font-size: 12px;
        color: #999;
    }}

    /* ── Items ── */
    .node-items {{
        margin: 4px 0;
        font-size: 13px;
    }}
    .item-icon {{ margin-right: 4px; }}
    .item-label {{ color: #666; margin-right: 6px; }}
    .item-tags {{
        display: inline-flex;
        flex-wrap: wrap;
        gap: 4px;
        margin-top: 2px;
    }}
    .item-tag {{
        display: inline-block;
        padding: 2px 8px;
        border-radius: 4px;
        font-size: 11px;
        font-family: 'SF Mono', 'Consolas', monospace;
    }}
    .delivery-tag {{
        background: #ffe0e0;
        color: #c0392b;
        border: 1px solid #f5c6cb;
    }}
    .pickup-tag {{
        background: #d4efdf;
        color: #1e8449;
        border: 1px solid #a9dfbf;
    }}

    /* ── Carrying ── */
    .node-carrying {{
        margin-top: 6px;
        font-size: 12px;
        color: #555;
        background: #fef9e7;
        padding: 6px 10px;
        border-radius: 4px;
        border: 1px solid #f9e79f;
    }}
    .carrying-icon {{ margin-right: 4px; }}
    .carrying-label {{ color: #888; margin-right: 4px; }}
    .carrying-items {{
        font-family: 'SF Mono', 'Consolas', monospace;
        font-size: 11px;
        color: #7d6608;
    }}

    /* ── Empty state ── */
    .empty-msg {{
        text-align: center;
        color: #999;
        padding: 40px;
        font-size: 16px;
    }}
    .no-selection {{
        display: flex;
        align-items: center;
        justify-content: center;
        height: 100%;
        color: #aaa;
        font-size: 18px;
        flex-direction: column;
        gap: 12px;
    }}
    .no-selection .big-icon {{ font-size: 64px; }}

    /* ── Scrollbar ── */
    ::-webkit-scrollbar {{ width: 6px; }}
    ::-webkit-scrollbar-thumb {{ background: #ccc; border-radius: 3px; }}
</style>
</head>
<body>

<div class="top-bar">
    <div>
        <h1>🚛 DPDP Executed Route Visualization</h1>
        <span style="font-size:13px;opacity:0.8;">Instance: {html_mod.escape(instance)}</span>
    </div>
    <div class="meta">
        <div>🕐 Generated: {html_mod.escape(generated_at)}</div>
        <div>🚛 {len(vehicles)} vehicles | 🔢 {total_nodes} executed nodes</div>
    </div>
</div>

<div class="main-container">
    <div class="sidebar" id="sidebar">
        <h3>🚛 Vehicles</h3>
        {sidebar_html}
    </div>
    <div class="content" id="content">
        <div class="no-selection" id="no-selection">
            <span class="big-icon">👈</span>
            <span>Select a vehicle from the sidebar to view its route</span>
        </div>
        {routes_html}
    </div>
</div>

<script>
    let activeVehicle = null;

    function selectVehicle(vehicleId) {{
        // Update sidebar cards
        document.querySelectorAll('.vehicle-summary-card').forEach(c => c.classList.remove('active'));
        const card = document.getElementById('card-' + vehicleId);
        if (card) card.classList.add('active');

        // Hide all routes
        document.querySelectorAll('.route-section').forEach(s => s.style.display = 'none');
        // Show selected route
        const route = document.getElementById('route-' + vehicleId);
        if (route) {{
            route.style.display = 'block';
            document.getElementById('no-selection').style.display = 'none';
        }}

        activeVehicle = vehicleId;
        // Scroll to top of content
        document.getElementById('content').scrollTop = 0;
    }}

    // Auto-select first vehicle on load
    document.addEventListener('DOMContentLoaded', function() {{
        const firstCard = document.querySelector('.vehicle-summary-card');
        if (firstCard) {{
            const vid = firstCard.id.replace('card-', '');
            selectVehicle(vid);
        }}
    }});
</script>

</body>
</html>'''


def main():
    """Main entry point."""
    if len(sys.argv) < 2:
        print(__doc__)
        print("ERROR: Please provide the path to executed_routes.json")
        sys.exit(1)

    input_path = sys.argv[1]
    if not os.path.exists(input_path):
        print(f"ERROR: File not found: {input_path}")
        sys.exit(1)

    # Default output path: same directory as input
    if len(sys.argv) >= 3:
        output_path = sys.argv[2]
    else:
        output_dir = os.path.dirname(input_path)
        output_path = os.path.join(output_dir, 'executed_routes.html')

    # Load data
    print(f"Loading: {input_path}")
    with open(input_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    instance = data.get('instance', 'Unknown')
    vehicles = data.get('vehicles', {})
    total_nodes = sum(v['total_nodes'] for v in vehicles.values())

    print(f"  Instance: {instance}")
    print(f"  Vehicles: {len(vehicles)}")
    print(f"  Total executed nodes: {total_nodes}")

    # Generate HTML
    print(f"Generating HTML...")
    html = generate_html(data)

    # Write output
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(html)

    print(f"✅ Output: {output_path}")
    print(f"   Open in browser: file:///{os.path.abspath(output_path).replace(os.sep, '/')}")


if __name__ == '__main__':
    main()
